apiVersion: batch/v1
kind: CronJob
metadata:
  name: reading-age-updater
  namespace: default
  labels:
    app: reading-age-updater
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: reading-age-updater
        spec:
          restartPolicy: Never
          nodeSelector:
            kubernetes.io/arch: amd64
          containers:
          - name: reading-age-updater
            image: kregistry.siwko.org:5000/mqtt-reader:latest
            imagePullPolicy: Always
            command: ["python", "update_reading_age.py"]
            env:
            - name: PGHOST
              value: prod-postgres-rw.default.svc.cluster.local
            - name: PGPORT
              value: "5432"
            - name: PGDATABASE
              value: sdr433
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: sdr433-role-credentials
                  key: username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: sdr433-role-credentials
                  key: password
